baseURL = 'https://jayliu.tech'
languageCode = 'zh-cn'
title = 'Jay Liu的随笔录'
theme = 'diary'

[params]
favicon = "images/favicon-egg.png"
subtitle = '日拱一卒，功不唐捐'
enableReadingTime=true
walineServer = "https://comment.jayliu.tech/"
  [params.contact]
    email = 'jayliu@tju.edu.cn'



[[menu.main]]
url = "/categories/"
name = "分类"
weight = 3

[[menu.main]]
url = "/tags/"
name = "标签"
weight = 2

[[menu.main]]
url = "/posts/"
name = "归档"
weight = 1

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
